logAppendsources = ./src/logappend.cpp
logReadsources = ./src/logRead.cpp

logAppendTarget = ./out/logappend
logReadTarget = ./out/logread

compiler = g++


logAppend:
	$(compiler) $(logAppendsources) -I./include/ -I./include/cryptopp/ -L./include/cryptopp890/ -lcryptopp -o $(logAppendTarget)


logRead:
	$(compiler) $(logReadsources) -I./include/ -o $(logReadTarget)


