logAppendsources = ./src/logappend.cpp
logReadsources = ./src/logRead.cpp

logAppendTarget = ./out/logappend.exe
logReadTarget = ./out/logread.exe

compiler = g++


logAppend:
	$(compiler) $(logAppendsources) -I./include/ -o $(logAppendTarget)


logRead:
	$(compiler) $(logReadsources) -I./include/ -o $(logReadTarget)
